services:
  - type: web
    name: esg-risk-predictor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: TOGETHER_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_PORT
        value: 5432
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_TOPIC
        value: esg_topic
      - key: KAFKA_SECURITY_PROTOCOL
        value: SASL_SSL
      - key: KAFKA_SASL_MECHANISM
        value: PLAIN
      - key: KAFKA_SASL_USERNAME
        value: $ConnectionString
      - key: KAFKA_SASL_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: 3.11